In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("skin clinic campaign.csv")

df.head()

,CustID,Gender,AgeGroup,Purchase_Last_Quarter,Unique_Products_Purchased,Response_to_Campaign
0,100001,Female,30-50,Yes,9,Yes
1,100002,Male,>50,Yes,15,No
2,100003,Male,>50,Yes,11,No
3,100004,Female,30-50,No,6,No
4,100005,Female,<30,Yes,13,Yes

In [16]:
print("Number of rows:", len(df))
print("Columns:")
print(df.columns.tolist())

Number of rows: 10000
Columns:
['CustID', 'Gender', 'AgeGroup', 'Purchase_Last_Quarter', 'Unique_Products_Purchased', 'Response_to_Campaign']

In [17]:
def response_rate_table(data, group_column):

    temp = data.copy()

    # Convert Yes/No campaign response into True/False
    temp["Responded"] = (
        temp["Response_to_Campaign"]
        .astype(str)
        .str.strip()
        .str.lower()
        .eq("yes")
    )

    # Group customers
    result = (
        temp.groupby(group_column, observed=False)
        .agg(
            Total_Customers=("CustID", "size"),
            Responded=("Responded", "sum"),
            Response_Rate=("Responded", "mean")
        )
        .reset_index()
    )

    # Convert response rate to percentage
    result["Response Rate (%)"] = (
        result["Response_Rate"] * 100
    ).round(2)

    # Remove temporary column
    result = result.drop(
        columns=["Response_Rate"]
    )

    return result

In [18]:
gender_analysis = response_rate_table(
    df,
    "Gender"
)

gender_analysis

   Gender  Total_Customers  Responded  Response Rate (%)
0  Female             6007       2629              43.77
1    Male             3993       1361              34.08

In [19]:
age_analysis = response_rate_table(
    df,
    "AgeGroup"
)

age_analysis

  AgeGroup  Total_Customers  Responded  Response Rate (%)
0    30-50             4992       2349              47.06
1      <30             2499        823              32.93
2      >50             2509        818              32.60

In [20]:
purchase_analysis = response_rate_table(
    df,
    "Purchase_Last_Quarter"
)

purchase_analysis

  Purchase_Last_Quarter  Total_Customers  Responded  Response Rate (%)
0                    No             3486        756              21.69
1                   Yes             6514       3234              49.65

In [21]:
df["Product_Usage"] = pd.cut(
    df["Unique_Products_Purchased"],
    bins=[0, 4, 8, np.inf],
    labels=["1-4", "5-8", ">8"]
)

In [22]:
df[
    [
        "Unique_Products_Purchased",
        "Product_Usage"
    ]
].head(10)

   Unique_Products_Purchased Product_Usage
0                          9            >8
1                         15            >8
2                         11            >8
3                          6           5-8
4                         13            >8
5                          5           5-8
6                         12            >8
7                          7           5-8
8                         15            >8
9                          7           5-8

In [23]:
df[
    [
        "Unique_Products_Purchased",
        "Product_Usage"
    ]
].head(10)

   Unique_Products_Purchased Product_Usage
0                          9            >8
1                         15            >8
2                         11            >8
3                          6           5-8
4                         13            >8
5                          5           5-8
6                         12            >8
7                          7           5-8
8                         15            >8
9                          7           5-8

In [26]:
product_analysis = response_rate_table(
    df,
    "Product_Usage"
)

product_analysis

  Product_Usage  Total_Customers  Responded  Response Rate (%)
0           1-4             2091        378              18.08
1           5-8             3703       1425              38.48
2            >8             4206       2187              52.00

In [27]:
output_file = "M10_PMLS_Assignment_2.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    gender_analysis.to_excel(
        writer,
        sheet_name="Gender",
        index=False
    )

    age_analysis.to_excel(
        writer,
        sheet_name="Age Group",
        index=False
    )

    purchase_analysis.to_excel(
        writer,
        sheet_name="Last Quarter",
        index=False
    )

    product_analysis.to_excel(
        writer,
        sheet_name="Product Usage",
        index=False
    )

print("Excel file created successfully!")

Excel file created successfully!

In [24]:
output_file = "M10_PMLS_Assignment_2.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    gender_analysis.to_excel(
        writer,
        sheet_name="Gender",
        index=False
    )

    age_analysis.to_excel(
        writer,
        sheet_name="Age Group",
        index=False
    )

    purchase_analysis.to_excel(
        writer,
        sheet_name="Last Quarter",
        index=False
    )

    product_analysis.to_excel(
        writer,
        sheet_name="Product Usage",
        index=False
    )

print("Excel file created successfully!")

NameError: name 'product_analysis' is not defined