In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("skin clinic campaign.csv")

df.head()

,CustID,Gender,AgeGroup,Purchase_Last_Quarter,Unique_Products_Purchased,Response_to_Campaign
0,100001,Female,30-50,Yes,9,Yes
1,100002,Male,>50,Yes,15,No
2,100003,Male,>50,Yes,11,No
3,100004,Female,30-50,No,6,No
4,100005,Female,<30,Yes,13,Yes

In [4]:
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (10000, 6)

Columns:
['CustID', 'Gender', 'AgeGroup', 'Purchase_Last_Quarter', 'Unique_Products_Purchased', 'Response_to_Campaign']

In [5]:
def response_rate_table(data, group_column):
    temp = data.copy()

    temp["Responded"] = (
        temp["Response_to_Campaign"]
        .str.strip()
        .str.lower()
        .eq("yes")
    )

    result = (
        temp.groupby(group_column, observed=False)
        .agg(
            Total_Customers=("CustID", "size"),
            Responded=("Responded", "sum"),
            Response_Rate=("Responded", "mean")
        )
        .reset_index()
    )

    result["Response Rate (%)"] = (
        result["Response_Rate"] * 100
    ).round(2)

    result = result.drop(columns="Response_Rate")

    return result

In [6]:
gender_analysis = response_rate_table(df, "Gender")

gender_analysis

   Gender  Total_Customers  Responded  Response Rate (%)
0  Female             6007       2629              43.77
1    Male             3993       1361              34.08

In [7]:
age_analysis = response_rate_table(df, "AgeGroup")

age_analysis

  AgeGroup  Total_Customers  Responded  Response Rate (%)
0    30-50             4992       2349              47.06
1      <30             2499        823              32.93
2      >50             2509        818              32.60

In [8]:
purchase_analysis = response_rate_table(
    df,
    "Purchase_Last_Quarter"
)

purchase_analysis

  Purchase_Last_Quarter  Total_Customers  Responded  Response Rate (%)
0                    No             3486        756              21.69
1                   Yes             6514       3234              49.65

In [9]:
df["Product_Usage"] = pd.cut(
    df["Unique_Products_Purchased"],
    bins=[0, 4, 8, np.inf],
    labels=["1-4", "5-8", ">8"]
)

df[[
    "Unique_Products_Purchased",
    "Product_Usage"
]].head()

   Unique_Products_Purchased Product_Usage
0                          9            >8
1                         15            >8
2                         11            >8
3                          6           5-8
4                         13            >8

In [10]:
product_analysis = response_rate_table(
    df,
    "Product_Usage"
)

product_analysis

  Product_Usage  Total_Customers  Responded  Response Rate (%)
0           1-4             2091        378              18.08
1           5-8             3703       1425              38.48
2            >8             4206       2187              52.00

In [11]:
print("GENDER VS CAMPAIGN RESPONSE")
display(gender_analysis)

print("AGE GROUP VS CAMPAIGN RESPONSE")
display(age_analysis)

print("PURCHASE IN LAST QUARTER VS CAMPAIGN RESPONSE")
display(purchase_analysis)

print("PRODUCT USAGE VS CAMPAIGN RESPONSE")
display(product_analysis)

GENDER VS CAMPAIGN RESPONSE

   Gender  Total_Customers  Responded  Response Rate (%)
0  Female             6007       2629              43.77
1    Male             3993       1361              34.08

AGE GROUP VS CAMPAIGN RESPONSE

  AgeGroup  Total_Customers  Responded  Response Rate (%)
0    30-50             4992       2349              47.06
1      <30             2499        823              32.93
2      >50             2509        818              32.60

PURCHASE IN LAST QUARTER VS CAMPAIGN RESPONSE

  Purchase_Last_Quarter  Total_Customers  Responded  Response Rate (%)
0                    No             3486        756              21.69
1                   Yes             6514       3234              49.65

PRODUCT USAGE VS CAMPAIGN RESPONSE

  Product_Usage  Total_Customers  Responded  Response Rate (%)
0           1-4             2091        378              18.08
1           5-8             3703       1425              38.48
2            >8             4206       2187              52.00

In [12]:
print("""
Campaign Analysis Summary

1. Female customers responded more frequently than male customers.

2. Customers aged 30-50 recorded the highest response rate
   among the three age groups.

3. Customers who purchased in the last quarter had a much
   higher response rate than customers who did not.

4. Response rate increased with product usage. Customers who
   purchased more than 8 unique products recorded the highest
   response rate.

These results suggest that recent purchasing activity and
higher product engagement are useful characteristics for
segmenting customers in future marketing campaigns.
""")

Campaign Analysis Summary

1. Female customers responded more frequently than male customers.

2. Customers aged 30-50 recorded the highest response rate
   among the three age groups.

3. Customers who purchased in the last quarter had a much
   higher response rate than customers who did not.

4. Response rate increased with product usage. Customers who
   purchased more than 8 unique products recorded the highest
   response rate.

These results suggest that recent purchasing activity and
higher product engagement are useful characteristics for
segmenting customers in future marketing campaigns.